version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - "./.env"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    tty: true
    networks:
      - local-net

networks:
  local-net:
    driver: bridge
